### PR TITLE
correct function_gradient docstring

### PR DESCRIPTION
**Pull request by kimauth**
According to the old docstring, `function_gradient` for vector valued functions does ∇N ⊗ u, while it really does u ⊗ ∇N. This makes a difference in which vector determines the columns and which one determines the rows.

### CODE REVIEW

**Comment by fredrikekre** [comment]
Should probably be clarified that this is when you use scalar base functions for a vector valued problem. Also, on line 138 `function_scalar_gradient` should be `function_gradient`.

**Comment by kimauth** [comment]
But the meaning of the docstring doesn't really change depending on whether it is `ScalarValues` or `VectorValues`, does it? For me the main take-away is that in the `function_gradient`  `u` spans the rows and `x` spans the columns. Or what would you document differently for vector base function?

**Comment by fredrikekre** [comment]
I mean that typically you would use `VectorValues` so then the first expression is still what is happening, just that the `N_i`s are vectors (meaning that `\nabla N_i`s are tensors).

**Comment by kimauth** [comment]
Modified the text a little, but I'm not so certain this actually makes it more understandable. What do you think @fredrikekre ?

**Pull request merged**
