### PR TITLE
Remove and deprecate nfields

### LINKED ISSUE #444: `Ferrite.nfields` should be called differently
```julia
grid = generate_grid(Quadrilateral, (1,1))
dh = DofHandler(grid)
push!(dh, :u, 2)
close!(dh)
```
```julia
julia> nfields(dh)
9

julia> Ferrite.nfields(dh)
1
```

The first one calls Julias [`nfields`](https://docs.julialang.org/en/v1/base/base/#Core.nfields).

### PR DESCRIPTION
**Pull request by termi-official**
Closes #444 .

### CODE REVIEW

**Comment by kimauth** [comment]
I had been thinking if we should entirely remove `nfields(dh)`. The only place it seems to be used is the soon-to-be-gone `DofHandler`. 
The docstrings for renumbering and the sparsity pattern should probably point to `getfieldnames(dh)`, as the order of the fields matters for them.

I have a hard time coming up with a use case where you'd only want to know the number of fields and nothing more. Usually you'd want to iterate over them and that's what `getfieldnames(dh)` should be used for I believe. 

What do you think?

**Comment by fredrikekre** [comment]
I was about to suggest the same.

**Comment by termi-official** [comment]
Thanks for the feedback on this. I have no strong opinion here. Just thought that it might be a nice convenience function. But I can also remove it if that is what we want to do.

**Comment by fredrikekre** [comment]
Looking at the small diff, it looks like we don't even use it much internally.

**Pull request merged**
