### PR TITLE
Update Downstream.yml to include testing FerriteInterfaceElements.jl

### PR DESCRIPTION
**Pull request by DRollin**
I just updated FerriteInterfaceElements.jl to Ferrite.jl 1.0.
This might be a good time to also test FerriteInterfaceElements.jl when testing Ferrite.jl.

### CODE REVIEW

**Comment by KnutAM** [comment]
Perhaps also add in the readme of Ferrite to increase visibility? 
Or wait until registered?

**Comment by DRollin** [comment]
I will add a note somewhere :+1: 
First, I want to have a first release of FerriteInterfaces.jl and then update to Ferrite#master.
(Currently the test still use `Lagrange` with three arguments)
Once that is working, I will add a note :smile:

**Comment by fredrikekre** [comment]
> update to Ferrite#master.

Looks like you need to do this first to make tests pass here.

**Comment by DRollin** [comment]
Yes, but first I wanted to fix version 1.0.0 of FerriteInterfaceElements.jl, so this version remains compatible wit Ferrite.jl 1.0.0.
I already started a PR, but I am not sure what needs to be done to release a version.

**Comment by DRollin** [comment]
I fixed the issue in FerriteInterfaceElements.jl

**Pull request merged**
