### PR TITLE
Fix ns_vs_diffeq fail

### PR DESCRIPTION
**Pull request by KnutAM**
Opened this to show the failure that happens when I just update the docs/Manifest.toml. 

I'm not sure if this is related to existing work on this example, so this PR can be considered an issue. But would be great if there is an easy fix, since this prevents updating the docs/Manifest... Feel free to just work on this branch or make a separate!

### CODE REVIEW

**Comment by koehlerson** [comment]
is this for https://github.com/Ferrite-FEM/Ferrite.jl/pull/917 ?

**Comment by KnutAM** [comment]
Too fast answer by @koehlerson :), wanted a pure CI run before filling the details

**Comment by termi-official** [comment]
The failure is basically https://github.com/Ferrite-FEM/Ferrite.jl/issues/508 surfacing, but now with an error message :) Before it was just a silent failure.

**Comment by KnutAM** [comment]
Then closing this as it sounds like it should be fixed soon!

**Pull request closed without merging**
