### PR TITLE
Shell on solid-face test

### LINKED ISSUE #899: Coupling shells to solid faces
It is quite uncommon, but sometimes you want to add a "skin" of shell elements on the face of a solid. One example of this which I have encountered, is to model sandwich composites with shell elements on the top and bottom surfaces of a solid foam core.

At the moment, it is not possible to this for higher order shells/solids. The reason for this is because shells (e.g Quadrilaterals) do not share a consistent definition of faces and edges with solids (e.g hexaherons). Note that it works for linear shells/solids since dofs are only distributed on nodes in this case.

MWE:
```
# Ferrite grid: Beam attached to face
# 3 ____ 4  4
# |      |  |   
# |      |  | (Beam attached to face)    
# 1 ____ 2  2

dim = 2
grid = generate_grid(Quadrilateral, (1,1))
line1 = Line((2,4))
grid = Grid([grid.cells[1], line1], grid.nodes)

order = 2
ip_quads = Lagrange{RefQuadrilateral, order}()#^dim
ip_shell = Lagrange{RefLine, order}()

dh = DofHandler(grid)
sdh_quads = SubDofHandler(dh, Set(1))
add!(sdh_quads, :u, ip_quads)
sdh_coh = SubDofHandler(dh, Set(2))
add!(sdh_coh, :u, ip_shell)
close!(dh)

dofsquad = zeros(Int, ndofs_per_cell(dh, 1))
dofsbeam = zeros(Int, ndofs_per_cell(dh, 2))

celldofs!(dofsquad, dh, 1)
celldofs!(dofsbeam, dh, 2)
@show dofsbeam # dofsbeam = [2, 3, 10]
```
As you can see, the dofs on the shell (or beam since this in 2d), contains a 10th dofs, but it should be the 6th dofs shared with the quad. Note that #789 would solve this (however with some annoying breaking changes)

### PR DESCRIPTION
**Pull request by lijas**
Test that the dofhandler distributes the dofs correctly when a shell (or beam) element is attached to the face of a solid.

Closes #899

### CODE REVIEW

**Comment by fredrikekre** [comment]
Nice that no changes were required haha

**Comment by termi-official** [comment]
Since I will need this in the not-so-far future, is there a good reference which explains how to couple the elements consistently? And can we add the theory to the docs?

**Comment by KnutAM** [comment]
> Since I will need this in the not-so-far future, is there a good reference which explains how to couple the elements consistently? And can we add the theory to the docs?

I feel that I don't understand the problem/question (i.e. how it could be done inconsistently): if two elements share the same entity (face/edge/vertex), they will be coupled. Of course a write-up of how the dof-distribution works in devdocs/topic guide could be nice!

**Comment by termi-official** [comment]
E.g. if you have a shell element with rotational and displacment degrees of freedom coupled to a solid element (straight line) for which  you just enforce that the displacement is the same, then the shell can freely rotate on the corner of the element, so you also have to put constraints on the rotational dofs.

**Comment by KnutAM** [comment]
Aha, now I understand the problem, but I don't know the answer.

**Comment by koehlerson** [comment]
Just don't is the answer 🙃

**Pull request merged**
