### PR TITLE
bugfix on CellIterator with given cellset

### PR DESCRIPTION
**Pull request by kimauth**

### CODE REVIEW

**Comment by fredrikekre** [comment]
I guess this code path could use a test then?

**Comment by kimauth** [comment]
I can't find any tests for the CellIterator. Is is possibly hidden within another test or do we never test it at all?

**Comment by fredrikekre** [comment]
Since before this patch it errored I guess that branch (e.g. CellIterator over a specific cellset) is not tested at all.

**Comment by kimauth** [comment]
Yeah, I was going to add a test for that branch after you commented. But then I couldn't find any tests for the CellIterator (not just for this branch). So I was wondering if we really never test it or if I am just missing where.

**Pull request merged**
